name: Deploy

'on':
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: cp .env.sample .env && yarn install && yarn build
        env:
          NEXT_PUBLIC_SITE_ORIGIN: ${{ vars.SITE_ORIGIN }}
      - uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
