name: Deploy

'on':
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '**/*.md'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: .tool-versions
      - run: cp .env.sample .env && npm ci && npm run test && npm run build
        env:
          NEXT_PUBLIC_SITE_ORIGIN: ${{ vars.SITE_ORIGIN }}
          NEXT_PUBLIC_GALLERY_DRIVE_FOLDER_ID: ${{ vars.GALLERY_DRIVE_FOLDER_ID }}
      - uses: w9jds/firebase-action@553f21e6a2d29596407ea70cc42add642645b803 # v14.5.1
        with:
          args: deploy
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
